[tool.poetry]
name = "fastapi-easy-cache"
version = "1.0.2"
description = ""
authors = ["DrEgg <dev@dregg.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
sqlalchemy = "^2.0.25"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
